force-app/main/default/objects/Supply_Order__c/Supply_Order__c.object-meta.xml
<CustomObject>
    <label>Supply Order</label>
    <nameField>
        <label>Supply Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supply Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supply_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>The status of a supply order.</description>
    <label>Order Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SupplyOrderTriggerHandler.cls
public with sharing class SupplyOrderTriggerHandler {
    
    /*
    * Verify that a shipping order's status cannot be changed from completed
    */
    public static void ValidateShippingStatusChange(List<Supply_Order__c> originalOrders, List<Supply_Order__c> newOrders) {
        for (Supply_Order__c order : newOrders) {
            if (order.Order_Status__c.toLowerCase() != 'complete') {
                for (Supply_Order__c original : originalOrders) {
                    if (order.Id == original.Id && original.Order_Status__c.toLowerCase() == 'complete') {
                        order.addError('Cannot change a completed order\'s status.');
                    }
                }
            }
        }
    }
    
}