force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <description>The customer&apos;s email.</description>
    <label>Customer Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Customer_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone_Number__c</fullName>
    <description>The customer&apos;s phone number.</description>
    <label>Customer Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerTriggerHandler.cls
// public with sharing class CustomerTriggerHandler {
    
//     /*
//     * Checks for duplicate customers upon insertion and merges them. Check is first name, last name,
//     * email, and phone to determine a match
//     */
//     public static void CheckForDuplicates(List<Customer__c> newCustomers, List<Customer__c> existingCustomer) {
//         List<Customer__c> matchingCustomers = new List<Customer__c>();

//         for (Customer__c nCustomer : newCustomers) {
//             for(Customer__c eCustomer : existingCustomer) {
//                 if (CompareCustomers(newCustomer, existingCustomer)) {
//                     matchingCustomers.add(newCustomer);
//                     matchingCustomers.add(existingCustomer);
//                 }
//             }
//         }

//         // Merge the matching customers
//         if (!matchingCustomers.isEmpty()) {
            
//         }
//     }

//     /*
//     * Compare the name, email, and phone of 2 customers to determine if it is a match
//     */
//     private Boolean CompareCustomers(Customer__c newCustomer, Customer__c existingCustomer) {
       
//         Boolean match = true;
       
//         if (existingCustomer.First_Name__c.toLowerCase() != newCustomer.First_Name__c.toLowerCase()) {
//             match = false;
//         }
//         if (existingCustomer.Last_Name__c.toLowerCase() != newCustomer.Last_Name__c.toLowerCase()) {
//             match = false;
//         }
//         if (existingCustomer.Customer_Email__c.toLowerCase() != newCustomer.Customer_Email__c.toLowerCase()){
//             match = false;
//         }
//         if (existingCustomer.Customer_Phone_Number__c != newCustomer.Customer_Phone_Number__c) {
//             match = false;
//         }    
//     }
// }