force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Date_Acquired__c.field-meta.xml
<CustomField>
    <fullName>Date_Acquired__c</fullName>
    <description>The date the item was acquired.</description>
    <label>Date Acquired</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The price of the item.</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>The physical store.</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/InventoryTrigger_Test.cls
@istest
public class InventoryTrigger_Test {
    
    static final string ITEM_NAME = '15 inch skilet circa 1820'; 
    static final string STORE_NAME = 'The Debug Store';

    Inventory__c newItem = new Inventory__c();

    @TestSetup
    static void setupData(){
        Inventory__c newItem = new Inventory__c();
        newItem.Name = ITEM_NAME;
        newItem.Date_Acquired__c = Date.today();
        // newItem.Store__c = new Store__c(Name='Generic Store');
        newItem.Price__c = 20.50;
    }

    @istest
    public TestInventoryDescriptionTrigger() {
        Database.SaveResult dbResult = Database.insert(newItem);
        if (!dbResult.isSuccess()) {
            System.debug('failed to insert inventory item');
        }
        else {
            System.assertEquals(ITEM_NAME, newItem.Notes);
        }
    }
}