force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Item_Notes__c.field-meta.xml
<CustomField>
    <fullName>Item_Notes__c</fullName>
    <description>Any notes or details related to the inventory item.</description>
    <label>Item Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/InventoryTriggerHandler.cls
public with sharing class InventoryTriggerHandler {

    /*
    * Upon insertion of a new inventory item, if the description is left blank
    * copy the name into the description.
    */
    public static void UpdateDescription(List<Inventory__c> triggerNew) {
        for(Inventory__c item : triggerNew) {
            if (String.isEmpty(item.Item_Notes__c)) {
                item.Item_Notes__c = item.Name;
            }
        }
    }
}